// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "roadmap": {
    "title": "Roadmap",
    "theme": {
      "timestamp": false
    }
  },
  "00-why-bitbucket-exists": {
    "title": "Why Bitbucket Exists",
    "theme": {
      "timestamp": false
    }
  },
  "01-bitbucket-platform-mental-model": {
    "title": "Bitbucket Platform Mental Model",
    "theme": {
      "timestamp": false
    }
  },
  "02-repositories-branches-and-pull-requests": {
    "title": "Repositories, Branches, And Pull Requests",
    "theme": {
      "timestamp": false
    }
  },
  "03-branch-permissions-merge-checks-and-review": {
    "title": "Branch Permissions, Merge Checks, And Review",
    "theme": {
      "timestamp": false
    }
  },
  "04-bitbucket-pipelines-deployments-and-secrets": {
    "title": "Bitbucket Pipelines, Deployments, And Secrets",
    "theme": {
      "timestamp": false
    }
  },
  "05-jira-governance-security-and-migration": {
    "title": "Jira, Governance, Security, And Migration",
    "theme": {
      "timestamp": false
    }
  },
  "06-advanced-bitbucket-operating-model": {
    "title": "Advanced Bitbucket Operating Model",
    "theme": {
      "timestamp": false
    }
  },
  "07-bitbucket-reference-library": {
    "title": "Bitbucket Reference Library",
    "theme": {
      "timestamp": false
    }
  }
}
