// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "mathematics": {
    "title": "Mathematics",
    "theme": {
      "timestamp": false
    }
  },
  "probability": {
    "title": "Probability",
    "theme": {
      "timestamp": false
    }
  },
  "statistics": {
    "title": "Statistics",
    "theme": {
      "timestamp": false
    }
  },
  "linear-algebra": {
    "title": "Linear Algebra",
    "theme": {
      "timestamp": false
    }
  },
  "optimization": {
    "title": "Optimization",
    "theme": {
      "timestamp": false
    }
  },
  "machine-learning": {
    "title": "Machine Learning",
    "theme": {
      "timestamp": false
    }
  },
  "deep-learning": {
    "title": "Deep Learning",
    "theme": {
      "timestamp": false
    }
  },
  "reinforcement-learning": {
    "title": "Reinforcement Learning",
    "theme": {
      "timestamp": false
    }
  },
  "llms": {
    "title": "LLMs",
    "theme": {
      "timestamp": false
    }
  },
  "ai-agents": {
    "title": "AI Agents",
    "theme": {
      "timestamp": false
    }
  },
  "mlops": {
    "title": "MLOps",
    "theme": {
      "timestamp": false
    }
  },
  "ai-infrastructure": {
    "title": "AI Infrastructure",
    "theme": {
      "timestamp": false
    }
  }
}
