// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "index": {
    "title": "Atlas",
    "type": "page",
    "theme": {
      "timestamp": false
    }
  },
  "computer-science": {
    "title": "Computer Science",
    "type": "page",
    "theme": {
      "timestamp": false
    }
  },
  "artificial-intelligence": {
    "title": "Artificial Intelligence",
    "type": "page",
    "theme": {
      "timestamp": false
    }
  },
  "cloud-infrastructure": {
    "title": "Cloud And Infrastructure",
    "type": "page",
    "theme": {
      "timestamp": false
    }
  },
  "software-development": {
    "title": "Software Development",
    "type": "page",
    "theme": {
      "timestamp": false
    }
  },
  "product-startups": {
    "title": "Product And Startups",
    "type": "page",
    "theme": {
      "timestamp": false
    }
  },
  "research": {
    "title": "Research",
    "type": "page",
    "theme": {
      "timestamp": false
    }
  }
}
