// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "index": {
    "title": "Overview",
    "theme": {
      "timestamp": false
    }
  },
  "roadmap": {
    "title": "Roadmap",
    "theme": {
      "timestamp": false
    }
  }
}
