// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "research-methodology": {
    "title": "Research Methodology",
    "theme": {
      "timestamp": false
    }
  },
  "scientific-thinking": {
    "title": "Scientific Thinking",
    "theme": {
      "timestamp": false
    }
  },
  "systems-thinking": {
    "title": "Systems Thinking",
    "theme": {
      "timestamp": false
    }
  },
  "first-principles-thinking": {
    "title": "First Principles Thinking",
    "theme": {
      "timestamp": false
    }
  },
  "knowledge-creation": {
    "title": "Knowledge Creation",
    "theme": {
      "timestamp": false
    }
  }
}
