// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "product-thinking": {
    "title": "Product Thinking",
    "theme": {
      "timestamp": false
    }
  },
  "product-management": {
    "title": "Product Management",
    "theme": {
      "timestamp": false
    }
  },
  "startup-fundamentals": {
    "title": "Startup Fundamentals",
    "theme": {
      "timestamp": false
    }
  },
  "business-models": {
    "title": "Business Models",
    "theme": {
      "timestamp": false
    }
  },
  "growth": {
    "title": "Growth",
    "theme": {
      "timestamp": false
    }
  },
  "finance": {
    "title": "Finance",
    "theme": {
      "timestamp": false
    }
  }
}
