// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "index": {
    "title": "Overview",
    "theme": {
      "timestamp": false
    }
  },
  "roadmap": {
    "title": "Roadmap",
    "theme": {
      "timestamp": false
    }
  },
  "00-why-hosted-code-collaboration": {
    "title": "Why Hosted Code Collaboration Exists",
    "theme": {
      "timestamp": false
    }
  },
  "01-what-is-github": {
    "title": "What Is GitHub?",
    "theme": {
      "timestamp": false
    }
  },
  "02-github-as-a-social-coding-platform": {
    "title": "GitHub As A Social Coding Platform",
    "theme": {
      "timestamp": false
    }
  },
  "03-repositories-and-visibility": {
    "title": "Repositories And Visibility",
    "theme": {
      "timestamp": false
    }
  },
  "04-issues-and-project-tracking": {
    "title": "Issues And Project Tracking",
    "theme": {
      "timestamp": false
    }
  },
  "05-pull-requests-as-review-units": {
    "title": "Pull Requests As Review Units",
    "theme": {
      "timestamp": false
    }
  },
  "06-code-review-workflows": {
    "title": "Code Review Workflows",
    "theme": {
      "timestamp": false
    }
  },
  "07-forks-and-contribution-flow": {
    "title": "Forks And Contribution Flow",
    "theme": {
      "timestamp": false
    }
  },
  "08-branches-and-protection-rules": {
    "title": "Branches And Protection Rules",
    "theme": {
      "timestamp": false
    }
  },
  "09-releases-and-tags": {
    "title": "Releases And Tags",
    "theme": {
      "timestamp": false
    }
  },
  "10-github-actions-foundations": {
    "title": "GitHub Actions Foundations",
    "theme": {
      "timestamp": false
    }
  },
  "11-workflows-jobs-and-steps": {
    "title": "Workflows, Jobs, And Steps",
    "theme": {
      "timestamp": false
    }
  },
  "12-runners-and-execution-environments": {
    "title": "Runners And Execution Environments",
    "theme": {
      "timestamp": false
    }
  },
  "13-secrets-and-environments": {
    "title": "Secrets And Environments",
    "theme": {
      "timestamp": false
    }
  },
  "14-ci-cd-patterns": {
    "title": "CI/CD Patterns",
    "theme": {
      "timestamp": false
    }
  },
  "15-packages-and-artifacts": {
    "title": "Packages And Artifacts",
    "theme": {
      "timestamp": false
    }
  },
  "16-pages-and-static-hosting": {
    "title": "Pages And Static Hosting",
    "theme": {
      "timestamp": false
    }
  },
  "17-security-alerts-and-dependabot": {
    "title": "Security Alerts And Dependabot",
    "theme": {
      "timestamp": false
    }
  },
  "18-codeowners-and-review-ownership": {
    "title": "CODEOWNERS And Review Ownership",
    "theme": {
      "timestamp": false
    }
  },
  "19-discussions-and-community": {
    "title": "Discussions And Community",
    "theme": {
      "timestamp": false
    }
  },
  "20-github-api-overview": {
    "title": "GitHub API Overview",
    "theme": {
      "timestamp": false
    }
  },
  "21-rest-vs-graphql": {
    "title": "REST Vs GraphQL",
    "theme": {
      "timestamp": false
    }
  },
  "22-webhooks-and-event-driven-automation": {
    "title": "Webhooks And Event-Driven Automation",
    "theme": {
      "timestamp": false
    }
  },
  "23-github-apps-and-oauth-apps": {
    "title": "GitHub Apps And OAuth Apps",
    "theme": {
      "timestamp": false
    }
  },
  "24-permissions-and-access-control": {
    "title": "Permissions And Access Control",
    "theme": {
      "timestamp": false
    }
  },
  "25-organizations-and-teams": {
    "title": "Organizations And Teams",
    "theme": {
      "timestamp": false
    }
  },
  "26-enterprise-governance": {
    "title": "Enterprise Governance",
    "theme": {
      "timestamp": false
    }
  },
  "27-open-source-maintenance": {
    "title": "Open Source Maintenance",
    "theme": {
      "timestamp": false
    }
  },
  "28-platform-design-decisions": {
    "title": "Platform Design Decisions",
    "theme": {
      "timestamp": false
    }
  },
  "29-github-limitations": {
    "title": "GitHub Limitations",
    "theme": {
      "timestamp": false
    }
  },
  "30-alternatives-to-github": {
    "title": "Alternatives To GitHub",
    "theme": {
      "timestamp": false
    }
  },
  "31-future-of-developer-platforms": {
    "title": "Future Of Developer Platforms",
    "theme": {
      "timestamp": false
    }
  },
  "32-research-questions-in-code-collaboration": {
    "title": "Research Questions In Code Collaboration",
    "theme": {
      "timestamp": false
    }
  }
}
