// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "frontend": {
    "title": "Frontend",
    "theme": {
      "timestamp": false
    }
  },
  "backend": {
    "title": "Backend",
    "theme": {
      "timestamp": false
    }
  },
  "apis": {
    "title": "APIs",
    "theme": {
      "timestamp": false
    }
  },
  "architecture": {
    "title": "Architecture",
    "theme": {
      "timestamp": false
    }
  },
  "design-patterns": {
    "title": "Design Patterns",
    "theme": {
      "timestamp": false
    }
  },
  "testing": {
    "title": "Testing",
    "theme": {
      "timestamp": false
    }
  },
  "performance-engineering": {
    "title": "Performance Engineering",
    "theme": {
      "timestamp": false
    }
  }
}
