// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "index": {
    "title": "Overview",
    "theme": {
      "timestamp": false
    }
  },
  "roadmap": {
    "title": "Roadmap",
    "theme": {
      "timestamp": false
    }
  },
  "00-why-version-control": {
    "title": "Why Version Control Exists",
    "theme": {
      "timestamp": false
    }
  },
  "01-what-is-git": {
    "title": "What Is Git?",
    "theme": {
      "timestamp": false
    }
  },
  "02-what-problem-does-git-solve": {
    "title": "What Problem Does Git Solve?",
    "theme": {
      "timestamp": false
    }
  },
  "03-history-of-version-control": {
    "title": "History Of Version Control",
    "theme": {
      "timestamp": false
    }
  },
  "04-centralized-vs-distributed-version-control": {
    "title": "Centralized Vs Distributed Version Control",
    "theme": {
      "timestamp": false
    }
  },
  "05-git-mental-model": {
    "title": "Git Mental Model",
    "theme": {
      "timestamp": false
    }
  },
  "06-repository-working-tree-index": {
    "title": "Repository, Working Tree, And Index",
    "theme": {
      "timestamp": false
    }
  },
  "07-basic-snapshot-workflow": {
    "title": "Basic Snapshot Workflow",
    "theme": {
      "timestamp": false
    }
  },
  "08-commits-as-history-nodes": {
    "title": "Commits As History Nodes",
    "theme": {
      "timestamp": false
    }
  },
  "09-reading-history": {
    "title": "Reading History",
    "theme": {
      "timestamp": false
    }
  },
  "10-branching-model": {
    "title": "Branching Model",
    "theme": {
      "timestamp": false
    }
  },
  "11-branch-workflows": {
    "title": "Branch Workflows",
    "theme": {
      "timestamp": false
    }
  },
  "12-merge-foundations": {
    "title": "Merge Foundations",
    "theme": {
      "timestamp": false
    }
  },
  "13-conflict-resolution": {
    "title": "Conflict Resolution",
    "theme": {
      "timestamp": false
    }
  },
  "14-rebase-foundations": {
    "title": "Rebase Foundations",
    "theme": {
      "timestamp": false
    }
  },
  "15-cherry-pick-and-patch-flow": {
    "title": "Cherry Pick And Patch Flow",
    "theme": {
      "timestamp": false
    }
  },
  "16-tags-and-release-points": {
    "title": "Tags And Release Points",
    "theme": {
      "timestamp": false
    }
  },
  "17-remotes-and-tracking-branches": {
    "title": "Remotes And Tracking Branches",
    "theme": {
      "timestamp": false
    }
  },
  "18-fetch-pull-and-push": {
    "title": "Fetch, Pull, And Push",
    "theme": {
      "timestamp": false
    }
  },
  "19-collaboration-protocols": {
    "title": "Collaboration Protocols",
    "theme": {
      "timestamp": false
    }
  },
  "20-git-object-model": {
    "title": "Git Object Model",
    "theme": {
      "timestamp": false
    }
  },
  "21-blobs": {
    "title": "Blobs",
    "theme": {
      "timestamp": false
    }
  },
  "22-trees": {
    "title": "Trees",
    "theme": {
      "timestamp": false
    }
  },
  "23-commits": {
    "title": "Commits",
    "theme": {
      "timestamp": false
    }
  },
  "24-refs-and-symbolic-refs": {
    "title": "Refs And Symbolic Refs",
    "theme": {
      "timestamp": false
    }
  },
  "25-head": {
    "title": "HEAD",
    "theme": {
      "timestamp": false
    }
  },
  "26-index-internals": {
    "title": "Index Internals",
    "theme": {
      "timestamp": false
    }
  },
  "27-object-hashing-and-integrity": {
    "title": "Object Hashing And Integrity",
    "theme": {
      "timestamp": false
    }
  },
  "28-packfiles": {
    "title": "Packfiles",
    "theme": {
      "timestamp": false
    }
  },
  "29-garbage-collection": {
    "title": "Garbage Collection",
    "theme": {
      "timestamp": false
    }
  },
  "30-reflog": {
    "title": "Reflog",
    "theme": {
      "timestamp": false
    }
  },
  "31-stash-internals": {
    "title": "Stash Internals",
    "theme": {
      "timestamp": false
    }
  },
  "32-submodules-and-subtrees": {
    "title": "Submodules And Subtrees",
    "theme": {
      "timestamp": false
    }
  },
  "33-hooks-and-automation": {
    "title": "Hooks And Automation",
    "theme": {
      "timestamp": false
    }
  },
  "34-bisect-and-debugging-history": {
    "title": "Bisect And Debugging History",
    "theme": {
      "timestamp": false
    }
  },
  "35-filtering-and-rewriting-history": {
    "title": "Filtering And Rewriting History",
    "theme": {
      "timestamp": false
    }
  },
  "36-large-repositories": {
    "title": "Large Repositories",
    "theme": {
      "timestamp": false
    }
  },
  "37-monorepo-considerations": {
    "title": "Monorepo Considerations",
    "theme": {
      "timestamp": false
    }
  },
  "38-security-and-signed-commits": {
    "title": "Security And Signed Commits",
    "theme": {
      "timestamp": false
    }
  },
  "39-distributed-systems-concepts-in-git": {
    "title": "Distributed Systems Concepts In Git",
    "theme": {
      "timestamp": false
    }
  },
  "40-git-design-decisions": {
    "title": "Git Design Decisions",
    "theme": {
      "timestamp": false
    }
  },
  "41-alternatives-to-git": {
    "title": "Alternatives To Git",
    "theme": {
      "timestamp": false
    }
  },
  "42-git-limitations": {
    "title": "Git Limitations",
    "theme": {
      "timestamp": false
    }
  },
  "43-future-of-version-control": {
    "title": "Future Of Version Control",
    "theme": {
      "timestamp": false
    }
  },
  "44-implementing-a-mini-git": {
    "title": "Implementing A Mini Git",
    "theme": {
      "timestamp": false
    }
  },
  "45-research-questions-in-version-control": {
    "title": "Research Questions In Version Control",
    "theme": {
      "timestamp": false
    }
  }
}
