// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "git": {
    "title": "Git",
    "theme": {
      "timestamp": false
    }
  },
  "github": {
    "title": "GitHub",
    "theme": {
      "timestamp": false
    }
  },
  "version-control-systems": {
    "title": "Version Control Systems",
    "theme": {
      "timestamp": false
    }
  },
  "data-structures": {
    "title": "Data Structures",
    "theme": {
      "timestamp": false
    }
  },
  "algorithms": {
    "title": "Algorithms",
    "theme": {
      "timestamp": false
    }
  },
  "operating-systems": {
    "title": "Operating Systems",
    "theme": {
      "timestamp": false
    }
  },
  "computer-architecture": {
    "title": "Computer Architecture",
    "theme": {
      "timestamp": false
    }
  },
  "digital-logic": {
    "title": "Digital Logic",
    "theme": {
      "timestamp": false
    }
  },
  "compilers": {
    "title": "Compilers",
    "theme": {
      "timestamp": false
    }
  },
  "programming-languages": {
    "title": "Programming Languages",
    "theme": {
      "timestamp": false
    }
  },
  "databases": {
    "title": "Databases",
    "theme": {
      "timestamp": false
    }
  },
  "networking": {
    "title": "Networking",
    "theme": {
      "timestamp": false
    }
  },
  "distributed-systems": {
    "title": "Distributed Systems",
    "theme": {
      "timestamp": false
    }
  },
  "security": {
    "title": "Security",
    "theme": {
      "timestamp": false
    }
  },
  "cryptography": {
    "title": "Cryptography",
    "theme": {
      "timestamp": false
    }
  },
  "software-engineering": {
    "title": "Software Engineering",
    "theme": {
      "timestamp": false
    }
  }
}
