import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const taxonomyPath = path.join(root, 'atlas', 'taxonomy.json')
const contentRoot = path.join(root, 'content')

const taxonomy = JSON.parse(await readFile(taxonomyPath, 'utf8'))
const generatedNotice = '// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.\n'

function titleCase(slug) {
  return slug
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

function quoteYaml(value) {
  return `"${String(value).replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`
}

function yamlArray(values) {
  if (!values || values.length === 0) {
    return ' []'
  }

  return `\n${values.map(value => `  - ${quoteYaml(value)}`).join('\n')}`
}

function trackStage(index) {
  if (index <= 9) return 'foundation'
  if (index <= 19) return 'practice'
  if (index <= 31) return 'internals'
  if (index <= 39) return 'systems'
  return 'research'
}

function trackDifficulty(index) {
  if (index <= 9) return 'beginner'
  if (index <= 25) return 'intermediate'
  if (index <= 39) return 'advanced'
  return 'research'
}

function frontmatter(metadata) {
  return [
    '---',
    `title: ${quoteYaml(metadata.title)}`,
    `description: ${quoteYaml(metadata.description)}`,
    `domain: ${quoteYaml(metadata.domain)}`,
    `category: ${quoteYaml(metadata.category)}`,
    `subcategory: ${quoteYaml(metadata.subcategory ?? '')}`,
    `difficulty: ${quoteYaml(metadata.difficulty)}`,
    `stage: ${quoteYaml(metadata.stage)}`,
    `type: ${quoteYaml(metadata.type)}`,
    `status: ${quoteYaml(metadata.status)}`,
    `tags:${yamlArray(metadata.tags)}`,
    `prerequisites:${yamlArray(metadata.prerequisites)}`,
    `related:${yamlArray(metadata.related)}`,
    `researchQuestions:${yamlArray(metadata.researchQuestions)}`,
    metadata.asIndexPage ? 'asIndexPage: true' : null,
    '---'
  ]
    .filter(Boolean)
    .join('\n')
}

function placeholderBody(title) {
  const sections = taxonomy.requiredSections
    .map(section => `## ${section}\n\n<!-- Content will be written manually. -->`)
    .join('\n\n')

  return `# ${title}\n\n> Scaffold status: this page defines structure only. Replace comments with manually researched content when the topic is ready.\n\n${sections}\n`
}

function document(metadata) {
  return `${frontmatter(metadata)}\n\n${placeholderBody(metadata.title)}`
}

async function writeIfMissing(filePath, contents) {
  await mkdir(path.dirname(filePath), { recursive: true })
  if (!existsSync(filePath)) {
    await writeFile(filePath, contents, 'utf8')
  }
}

async function writeGenerated(filePath, contents) {
  await mkdir(path.dirname(filePath), { recursive: true })
  await writeFile(filePath, contents, 'utf8')
}

function metaFile(record) {
  return `${generatedNotice}export default ${JSON.stringify(record, null, 2)}\n`
}

function metaEntry(title, extra = {}) {
  return {
    title,
    ...extra,
    theme: {
      ...(extra.theme ?? {}),
      timestamp: false
    }
  }
}

function topicMetadata(domain, topic, overrides = {}) {
  return {
    title: overrides.title ?? topic.title,
    description:
      overrides.description ??
      `Placeholder scaffold for ${topic.title} inside ${domain.title}.`,
    domain: domain.title,
    category: topic.title,
    subcategory: overrides.subcategory ?? '',
    difficulty: overrides.difficulty ?? taxonomy.project.defaultDifficulty,
    stage: overrides.stage ?? taxonomy.project.defaultStage,
    type: overrides.type ?? 'topic',
    status: 'scaffold',
    tags: overrides.tags ?? [domain.slug, topic.slug],
    prerequisites: overrides.prerequisites ?? [],
    related: overrides.related ?? [],
    researchQuestions: overrides.researchQuestions ?? [],
    asIndexPage: overrides.asIndexPage ?? false
  }
}

async function createHome() {
  const home = `---
title: "First Principles Atlas"
description: "Scaffold for a long-term first-principles knowledge infrastructure."
type: "system"
status: "scaffold"
---

# First Principles Atlas

<p className="atlas-kicker">A structure-first repository for manually authored technical knowledge, research maps, and future original insight.</p>

<div className="atlas-home-grid">
  <section className="atlas-home-panel">
    <h3>Knowledge Source</h3>
    <p>MDX files live in Git and remain portable, reviewable, searchable, and versioned.</p>
  </section>
  <section className="atlas-home-panel">
    <h3>Taxonomy</h3>
    <p>The topic tree starts in <code>atlas/taxonomy.json</code> and generates stable placeholder routes.</p>
  </section>
  <section className="atlas-home-panel">
    <h3>Quality Gates</h3>
    <p>Validation, tests, build checks, and Pagefind indexing protect the structure as it grows.</p>
  </section>
</div>

## Initial Domains

- [Computer Science](/computer-science)
- [Artificial Intelligence](/artificial-intelligence)
- [Cloud And Infrastructure](/cloud-infrastructure)
- [Software Development](/software-development)
- [Product And Startups](/product-startups)
- [Research](/research)
`

  await writeIfMissing(path.join(contentRoot, 'index.mdx'), home)
}

async function createDomain(domain) {
  const domainDir = path.join(contentRoot, domain.slug)
  const meta = {
    index: metaEntry('Overview', { theme: { toc: true } })
  }

  await writeIfMissing(
    path.join(domainDir, 'index.mdx'),
    document({
      title: domain.title,
      description: domain.description,
      domain: domain.title,
      category: domain.title,
      subcategory: '',
      difficulty: taxonomy.project.defaultDifficulty,
      stage: 'orientation',
      type: 'domain',
      status: 'scaffold',
      tags: [domain.slug],
      prerequisites: [],
      related: [],
      researchQuestions: [],
      asIndexPage: true
    })
  )

  for (const topic of domain.children) {
    meta[topic.slug] = metaEntry(topic.title)
    await createTopic(domain, topic, domainDir)
  }

  await writeGenerated(path.join(domainDir, '_meta.js'), metaFile(meta))
}

async function createTopic(domain, topic, domainDir) {
  const topicDir = path.join(domainDir, topic.slug)
  const meta = {
    index: metaEntry('Overview'),
    roadmap: metaEntry('Roadmap')
  }

  await writeIfMissing(
    path.join(topicDir, 'index.mdx'),
    document(
      topicMetadata(domain, topic, {
        title: topic.title,
        description: topic.description ?? `Placeholder scaffold for ${topic.title}.`,
        type: 'topic-index',
        stage: 'orientation',
        asIndexPage: true
      })
    )
  )

  await writeIfMissing(
    path.join(topicDir, 'roadmap.mdx'),
    document(
      topicMetadata(domain, topic, {
        title: `${topic.title} Roadmap`,
        description: `Roadmap placeholder for sequencing ${topic.title} learning and research work.`,
        type: 'roadmap',
        stage: 'foundation',
        tags: [domain.slug, topic.slug, 'roadmap']
      })
    )
  )

  if (Array.isArray(topic.track)) {
    for (const [index, item] of topic.track.entries()) {
      meta[item.slug] = metaEntry(item.title)
      const related = []
      if (topic.track[index - 1]) related.push(`./${topic.track[index - 1].slug}`)
      if (topic.track[index + 1]) related.push(`./${topic.track[index + 1].slug}`)

      await writeIfMissing(
        path.join(topicDir, `${item.slug}.mdx`),
        document(
          topicMetadata(domain, topic, {
            title: item.title,
            description: `Placeholder scaffold for ${item.title} in the ${topic.title} learning track.`,
            subcategory: topic.title,
            type: 'track-topic',
            difficulty: trackDifficulty(index),
            stage: trackStage(index),
            tags: [domain.slug, topic.slug, item.slug.replace(/^\d+-/, '')],
            related
          })
        )
      )
    }
  }

  await writeGenerated(path.join(topicDir, '_meta.js'), metaFile(meta))
}

async function createRootMeta() {
  const meta = {
    index: metaEntry('Atlas', { type: 'page' })
  }

  for (const domain of taxonomy.domains) {
    meta[domain.slug] = metaEntry(domain.title, { type: 'page' })
  }

  await writeGenerated(path.join(contentRoot, '_meta.js'), metaFile(meta))
}

await createHome()
await createRootMeta()

for (const domain of taxonomy.domains) {
  await createDomain(domain)
}

console.log(`Generated atlas scaffold for ${taxonomy.domains.length} domains.`)
