// Generated by scripts/generate-atlas.mjs. Edit atlas/taxonomy.json instead.
export default {
  "index": {
    "title": "Overview",
    "theme": {
      "toc": true,
      "timestamp": false
    }
  },
  "linux": {
    "title": "Linux",
    "theme": {
      "timestamp": false
    }
  },
  "devops": {
    "title": "DevOps",
    "theme": {
      "timestamp": false
    }
  },
  "docker": {
    "title": "Docker",
    "theme": {
      "timestamp": false
    }
  },
  "kubernetes": {
    "title": "Kubernetes",
    "theme": {
      "timestamp": false
    }
  },
  "aws": {
    "title": "AWS",
    "theme": {
      "timestamp": false
    }
  },
  "gcp": {
    "title": "GCP",
    "theme": {
      "timestamp": false
    }
  },
  "azure": {
    "title": "Azure",
    "theme": {
      "timestamp": false
    }
  },
  "observability": {
    "title": "Observability",
    "theme": {
      "timestamp": false
    }
  },
  "sre": {
    "title": "SRE",
    "theme": {
      "timestamp": false
    }
  }
}
